version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout
      colors: true

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - mnd
    - goprintffuncname
    - copyloopvar
  
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/cachemir/cachemir
    errcheck:
      check-type-assertions: true
      check-blank: true
    
    govet:
      enable-all: true
      enable:
        - shadow
      disable:
        - fieldalignment
    
    gocyclo:
      min-complexity: 15
    
    dupl:
      threshold: 100
    
    goconst:
      min-len: 3
      min-occurrences: 3
    
    misspell:
      locale: US
    
    lll:
      line-length: 120
    
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
  
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - mnd
          - funlen
          - goconst
      - path: 'cmd/'
        linters:
          - gochecknoinits

formatters:
  enable:
    - gofmt
    - goimports
