blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/cachemir/cachemir/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/cachemir/cachemir/security/advisories/new
    about: Report security vulnerabilities privately
  - name: 📚 Documentation
    url: https://github.com/cachemir/cachemir/blob/main/README.md
    about: Read the documentation and guides
