name: Docker

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  metadata:
    name: Generate Image Metadata
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    outputs:
      json: ${{ steps.meta.outputs.json }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: metadata
    strategy:
      matrix:
        tag: ${{ fromJson(needs.metadata.outputs.json).tags }}
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    
    - name: Debug Info
      run: |
        echo "Tags: ${{ fromJson(needs.metadata.outputs.json).tags }}"
        echo "Labels: ${{ fromJson(needs.metadata.outputs.json).labels }}"
        
    - uses: dagger/dagger-for-github@v8.3.0
      env:
        TAG: ${{ matrix.tag }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      with:
        version: "latest"
        module: github.com/kdihalas/dagger/go
        args: --source=. publish --path=cmd/server/main.go --registry=${{ env.REGISTRY }} --imageName=${{ env.TAG }} --username=${{ github.actor }} --password="env://PASSWORD"
        cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}