name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dagger/dagger-for-github@v8.4.1
        with:
          version: "latest"
          module: github.com/kdihalas/dagger/release-please
          args: --token env://GITHUB_TOKEN run --release-type=go --repo-url=https://github.com/${{ github.repository }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          enable-github-summary: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}